name = "STACCube"
uuid = "285b90eb-66e7-49f7-b676-58f042805622"
authors = ["Felix Cremer <fcr"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[targets]
test = ["Test"]
